on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/*
      - _config.yml
      - assets/**
      - content/**
      - data/**
      - i18n/**
      - layouts/**
      - static/**

name: Site Build Testing

jobs:
  test:
    name: Testing
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout ScratchAddons/website-v2
        uses: actions/checkout@v2
        with:
          path: repo
      - name: Checkout ScratchAddons/website-v2-script
        uses: actions/checkout@v2
        with:
          repository: ScratchAddons/website-v2-script
          path: script
      - name: Checkout ScratchAddons/website-i18n
        uses: actions/checkout@v2
        with:
          repository: ScratchAddons/website-i18n
          path: i18n

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x 
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Execute preparation script
        run: | 
          echo Running...
          cd repo
          bash ../script/sh/hugo-deploy-site.sh

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: Build site
        run: |
          cd repo
          hugo --gc --minify --config config.yml,config-prod.yml
          
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: ./repo/public
      - name: Upload whole repo (to check i18n)
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: ./repo